/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiBoxViewPaginatedResponse } from '../../models/api-box-view-paginated-response';
import { ApiGetPagedBoxesRequest } from '../../models/api-get-paged-boxes-request';

export interface ApiBoxesPagedBoxesPost$Params {
  body?: ApiGetPagedBoxesRequest;
}

export function apiBoxesPagedBoxesPost(
  http: HttpClient,
  rootUrl: string,
  params?: ApiBoxesPagedBoxesPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ApiBoxViewPaginatedResponse>> {
  const rb = new RequestBuilder(rootUrl, apiBoxesPagedBoxesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'text/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiBoxViewPaginatedResponse>;
    }),
  );
}

apiBoxesPagedBoxesPost.PATH = '/api/Boxes/paged-boxes';
