/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAuthCurrentUserGet } from '../fn/auth/api-auth-current-user-get';
import { ApiAuthCurrentUserGet$Params } from '../fn/auth/api-auth-current-user-get';
import { apiAuthCurrentUserGet$Plain } from '../fn/auth/api-auth-current-user-get-plain';
import { ApiAuthCurrentUserGet$Plain$Params } from '../fn/auth/api-auth-current-user-get-plain';
import { apiAuthLoginPost } from '../fn/auth/api-auth-login-post';
import { ApiAuthLoginPost$Params } from '../fn/auth/api-auth-login-post';
import { apiAuthLoginPost$Plain } from '../fn/auth/api-auth-login-post-plain';
import { ApiAuthLoginPost$Plain$Params } from '../fn/auth/api-auth-login-post-plain';
import { apiAuthRegisterPost } from '../fn/auth/api-auth-register-post';
import { ApiAuthRegisterPost$Params } from '../fn/auth/api-auth-register-post';
import { apiAuthRegisterPost$Plain } from '../fn/auth/api-auth-register-post-plain';
import { ApiAuthRegisterPost$Plain$Params } from '../fn/auth/api-auth-register-post-plain';
import { ApiApplicationUser } from '../models/api-application-user';
import { ApiAuthResult } from '../models/api-auth-result';

@Injectable({ providedIn: 'root' })
export class AuthApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAuthLoginPost()` */
  static readonly ApiAuthLoginPostPath = '/api/Auth/Login';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthLoginPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost$Plain$Response(
    params?: ApiAuthLoginPost$Plain$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<ApiAuthResult>> {
    return apiAuthLoginPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthLoginPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost$Plain(
    params?: ApiAuthLoginPost$Plain$Params,
    context?: HttpContext,
  ): Observable<ApiAuthResult> {
    return this.apiAuthLoginPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiAuthResult>): ApiAuthResult => r.body),
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthLoginPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost$Response(
    params?: ApiAuthLoginPost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<ApiAuthResult>> {
    return apiAuthLoginPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthLoginPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost(
    params?: ApiAuthLoginPost$Params,
    context?: HttpContext,
  ): Observable<ApiAuthResult> {
    return this.apiAuthLoginPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiAuthResult>): ApiAuthResult => r.body),
    );
  }

  /** Path part for operation `apiAuthRegisterPost()` */
  static readonly ApiAuthRegisterPostPath = '/api/Auth/Register';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthRegisterPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthRegisterPost$Plain$Response(
    params?: ApiAuthRegisterPost$Plain$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<boolean>> {
    return apiAuthRegisterPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthRegisterPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthRegisterPost$Plain(
    params?: ApiAuthRegisterPost$Plain$Params,
    context?: HttpContext,
  ): Observable<boolean> {
    return this.apiAuthRegisterPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body),
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthRegisterPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthRegisterPost$Response(
    params?: ApiAuthRegisterPost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<boolean>> {
    return apiAuthRegisterPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthRegisterPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthRegisterPost(
    params?: ApiAuthRegisterPost$Params,
    context?: HttpContext,
  ): Observable<boolean> {
    return this.apiAuthRegisterPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body),
    );
  }

  /** Path part for operation `apiAuthCurrentUserGet()` */
  static readonly ApiAuthCurrentUserGetPath = '/api/Auth/Current-user';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthCurrentUserGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthCurrentUserGet$Plain$Response(
    params?: ApiAuthCurrentUserGet$Plain$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<ApiApplicationUser>> {
    return apiAuthCurrentUserGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthCurrentUserGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthCurrentUserGet$Plain(
    params?: ApiAuthCurrentUserGet$Plain$Params,
    context?: HttpContext,
  ): Observable<ApiApplicationUser> {
    return this.apiAuthCurrentUserGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiApplicationUser>): ApiApplicationUser => r.body),
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthCurrentUserGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthCurrentUserGet$Response(
    params?: ApiAuthCurrentUserGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<ApiApplicationUser>> {
    return apiAuthCurrentUserGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthCurrentUserGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthCurrentUserGet(
    params?: ApiAuthCurrentUserGet$Params,
    context?: HttpContext,
  ): Observable<ApiApplicationUser> {
    return this.apiAuthCurrentUserGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiApplicationUser>): ApiApplicationUser => r.body),
    );
  }
}
