export enum AuthToastEnum {
  SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILED = 'SIGN_IN_FAILED',
  SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILED = 'SIGN_UP_FAILED',
  ALREADY_AUTHORIZED = 'ALREADY_AUTHORIZED',
  AUTHORIZATION_REQUIRED = 'AUTHORIZATION_REQUIRED',
}
