/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiBoxView } from '../models/api-box-view';
export interface ApiBoxViewPaginatedResponse {
  items?: Array<ApiBoxView> | null;
  totalCount?: number;
}
