/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiCreateBoxRequest {
  description?: string | null;
  discussionEndDate: string;
  endDate: string;
  giftPurchaseEndDate: string;
  icon?: string | null;
  location?: string | null;
  maxGiftValue: number;
  minGiftValue: number;
  name: string;
  randomizationDate: string;
  startDate: string;
}
