/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Модель коробки в системе "Секретный Санта".
 */
export interface ApiBoxView {

  /**
   * Описание коробки.
   */
  description?: string | null;

  /**
   * Иконка, ассоциированная с коробкой.
   */
  icon?: string | null;

  /**
   * Приватный идентификатор коробки.
   */
  id?: string;

  /**
   * Публичный идентификатор коробки, который используется для доступа к коробке.
   */
  idCode?: string | null;

  /**
   * Дата окончания приема участников в коробку.
   */
  inviteEndDate?: string;

  /**
   * Место проведения обмена подарками.
   */
  location?: string | null;

  /**
   * Максимальная сумма подарка, которую необходимо подарить.
   */
  maxGiftValue?: number;

  /**
   * Дата сбора участников для обмена подарками.
   */
  meetingDate?: string;

  /**
   * Минимальная сумма подарка, которую необходимо подарить.
   */
  minGiftValue?: number;

  /**
   * Наименование коробки.
   */
  name?: string | null;
}
