/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiGenderEnum } from '../models/api-gender-enum';
export interface ApiSignUpRequest {
  email?: string | null;
  firstName?: string | null;
  gender?: ApiGenderEnum;
  lastName?: string | null;
  password?: string | null;
}
