/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiParticipantView {

  /**
   * Электронная почта участника.
   */
  email?: string | null;

  /**
   * Имя участника.
   */
  firstName?: string | null;

  lastName?: string | null;
  
  /**
   * Уникальный идентификатор участника.
   */
  id?: string;
}

