/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiInterestView {

  /**
   * Уникальный идентификатор
   */
  id?: number;

  /**
   * Название интереса
   */
  title?: string | null;
}
