/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiCreateBoxRequest {
  description?: string | null;
  icon?: string | null;
  inviteEndDate: string;
  location?: string | null;
  maxGiftValue: number;
  meetingDate: string;
  minGiftValue: number;
  name: string;
  showResults: boolean;
}
