/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiParticipantShortView } from '../models/api-participant-short-view';

/**
 * Детали коробки в системе "Секретный Санта".
 */
export interface ApiBoxDetail {
  canStartRandomize?: boolean;

  /**
   * Описание коробки.
   */
  description?: string | null;

  /**
   * Иконка, ассоциированная с коробкой.
   */
  icon?: string | null;

  /**
   * Приватный идентификатор коробки.
   */
  id?: string;

  /**
   * Дата окончания приема участников в коробку.
   */
  inviteEndDate?: string;
  isExpiredDate?: boolean;

  /**
   * Место проведения обмена подарками.
   */
  location?: string | null;

  /**
   * Максимальная сумма подарка, которую необходимо подарить.
   */
  maxGiftValue?: number;

  /**
   * Дата сбора участников для обмена подарками.
   */
  meetingDate?: string;

  /**
   * Минимальная сумма подарка, которую необходимо подарить.
   */
  minGiftValue?: number;

  /**
   * Наименование коробки.
   */
  name?: string | null;

  /**
   * Список участников коробки.
   */
  participants?: Array<ApiParticipantShortView> | null;
  showResults?: boolean;
  randomizationStarted?: boolean;
}
