/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Запрос для входа пользователя в систему.
 */
export interface ApiSignInRequest {

  /**
   * Электронная почта пользователя.
   */
  email: string;

  /**
   * Пароль пользователя.
   */
  password: string;
}
