/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiParticipant } from '../models/api-participant';
export interface ApiBoxDetail {
  description?: string | null;
  icon?: string | null;
  id?: string;
  idCode?: string | null;
  inviteEndDate?: string;
  location?: string | null;
  maxGiftValue?: number;
  meetingDate?: string;
  minGiftValue?: number;
  name?: string | null;
  participants?: Array<ApiParticipant> | null;
}
