/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiBoxView } from '../models/api-box-view';

/**
 * Представляет ответ с результатами пагинации
 */
export interface ApiBoxViewPaginatedResponse {

  /**
   * Список элементов, принадлежащих к текущей странице
   */
  items?: Array<ApiBoxView> | null;

  /**
   * Общее количество элементов в наборе данных, не зависящее от пагинации
   */
  totalCount?: number;
}
