/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiBoxShortInfo } from '../models/api-box-short-info';
import { ApiGenderEnum } from '../models/api-gender-enum';
import { ApiInterestView } from '../models/api-interest-view';
export interface ApiParticipantView {

  /**
   * Поле "О себе"
   */
  aboutMe?: string | null;

  /**
   * Список коробок
   */
  boxes?: Array<ApiBoxShortInfo> | null;
  email?: string | null;

  /**
   * Имя пользователя
   */
  firstName?: string | null;
  gender?: ApiGenderEnum;
  id?: string | null;

  /**
   * Список интересов
   */
  interests?: Array<ApiInterestView> | null;

  /**
   * Фамилия пользователя
   */
  lastName?: string | null;
}
