/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Модель коробки в системе "Секретный Санта".
 */
export interface ApiBoxShortInfo {

  /**
   * Иконка, ассоциированная с коробкой.
   */
  icon?: string | null;

  /**
   * Приватный идентификатор коробки.
   */
  id?: string;

  /**
   * Наименование коробки.
   */
  name?: string | null;
}
