/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiParticipantShortView {
  email?: string | null;

  /**
   * Имя пользователя
   */
  firstName?: string | null;
  id?: string | null;

  /**
   * Фамилия пользователя
   */
  lastName?: string | null;
}
