/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO для обновления данных пользователя.
 */
export interface ApiUpdateUserRequest {

  /**
   * Поле "О себе".
   */
  aboutMe?: string | null;

  /**
   * Имя пользователя.
   */
  firstName?: string | null;

  /**
   * Фамилия пользователя.
   */
  lastName?: string | null;
}
