/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiGenderEnum } from '../models/api-gender-enum';
export interface ApiApplicationUser {
  accessFailedCount?: number;
  concurrencyStamp?: string | null;
  email?: string | null;
  emailConfirmed?: boolean;
  firstName?: string | null;
  gender?: ApiGenderEnum;
  id?: string | null;
  lastName?: string | null;
  lockoutEnabled?: boolean;
  lockoutEnd?: string | null;
  normalizedEmail?: string | null;
  normalizedUserName?: string | null;
  passwordHash?: string | null;
  phoneNumber?: string | null;
  phoneNumberConfirmed?: boolean;
  securityStamp?: string | null;
  twoFactorEnabled?: boolean;
  userName?: string | null;
}
