/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiGenderEnum } from '../models/api-gender-enum';

/**
 * Запрос для регистрации нового пользователя.
 */
export interface ApiSignUpRequest {

  /**
   * Электронная почта пользователя.
   */
  email: string;

  /**
   * Имя пользователя.
   */
  firstName: string;
  gender: ApiGenderEnum;

  /**
   * Фамилия пользователя.
   */
  lastName: string;

  /**
   * Пароль пользователя.
   */
  password: string;
}
