/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Перечисление, представляющее пол.
 */
export enum ApiGenderEnum {
  $0 = 0,
  $1 = 1,
  $2 = 2
}
