/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiBoxView {
  description?: string | null;
  endDate?: string;
  giftPurchaseEndDate?: string;
  icon?: string | null;
  id?: string;
  idCode?: string | null;
  location?: string | null;
  maxGiftValue?: number;
  minGiftValue?: number;
  name?: string | null;
  randomizationDate?: string;
  startDate?: string;
}
