/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Запрос для получения списка коробок с пагинацией.
 */
export interface ApiGetPagedBoxesRequest {

  /**
   * Наименование коробки
   */
  name?: string | null;

  /**
   * Номер страницы для пагинации
   */
  page?: number;

  /**
   * Размер страницы для пагинации
   */
  size?: number;
}
