/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ApiConfiguration } from './api-configuration';
export { BaseService } from './base-service';
export { RequestBuilder } from './request-builder';
export type { StrictHttpResponse } from './strict-http-response';
export { ApiModule } from './api.module';
export type { ApiApplicationUser } from './models/api-application-user';
export type { ApiAuthResult } from './models/api-auth-result';
export type { ApiBoxDetail } from './models/api-box-detail';
export type { ApiBoxView } from './models/api-box-view';
export type { ApiBoxViewPaginatedResponse } from './models/api-box-view-paginated-response';
export type { ApiCreateBoxRequest } from './models/api-create-box-request';
export { ApiGenderEnum } from './models/api-gender-enum';
export type { ApiGetPagedBoxesRequest } from './models/api-get-paged-boxes-request';
export type { ApiParticipant } from './models/api-participant';
export type { ApiSignInRequest } from './models/api-sign-in-request';
export type { ApiSignUpRequest } from './models/api-sign-up-request';
export { AuthApiService } from './services/auth-api.service';
export { BoxesApiService } from './services/boxes-api.service';
