/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiParticipantShortView } from '../../models/api-participant-short-view';

export interface ApiBoxesBoxIdMyGiverGet$Plain$Params {

/**
 * ID коробки.
 */
  boxId: string;
}

export function apiBoxesBoxIdMyGiverGet$Plain(http: HttpClient, rootUrl: string, params: ApiBoxesBoxIdMyGiverGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiParticipantShortView>> {
  const rb = new RequestBuilder(rootUrl, apiBoxesBoxIdMyGiverGet$Plain.PATH, 'get');
  if (params) {
    rb.path('boxId', params.boxId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiParticipantShortView>;
    })
  );
}

apiBoxesBoxIdMyGiverGet$Plain.PATH = '/api/Boxes/{boxId}/my-giver';
