/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiBoxPairing } from '../../models/api-box-pairing';

export interface ApiBoxesBoxIdRandomizeParticipantsPost$Plain$Params {
  boxId: string;
}

export function apiBoxesBoxIdRandomizeParticipantsPost$Plain(http: HttpClient, rootUrl: string, params: ApiBoxesBoxIdRandomizeParticipantsPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiBoxPairing>> {
  const rb = new RequestBuilder(rootUrl, apiBoxesBoxIdRandomizeParticipantsPost$Plain.PATH, 'post');
  if (params) {
    rb.path('boxId', params.boxId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiBoxPairing>;
    })
  );
}

apiBoxesBoxIdRandomizeParticipantsPost$Plain.PATH = '/api/Boxes/{boxId}/randomize-participants';
